### ISSUE TITLE
Sample App section in README.md pointing to wrong directory path

### ISSUE THREAD

**Issue by sumitparakh** [microsoft/PageTour-SDK#6]
Open sample-app section in README.md file
https://github.com/microsoft/PageTour-SDK#sample-app

It says, `got to PageTour-SDK/sample run npm install and then npm run start`

sample folder is inside apps folder, so shouldn't it be `PageTour-SDK/apps/sample`?

Also there is a spelling mistake (`got` should be `go`)

**Comment by Kartik2016** [comment]
Thank you for raising the issue and the corresponding fix!
Reviewed the PR and added comments.
